// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL6IQNSwRd2EDt77YJBd-T3giehpSJfck',
    appId: '1:974311107190:web:df854ace2c089c7ddd4d57',
    messagingSenderId: '974311107190',
    projectId: 'gotime-15974',
    authDomain: 'gotime-15974.firebaseapp.com',
    storageBucket: 'gotime-15974.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAkssUkcxEVk4yC0biA-alQfViWrHbtmo',
    appId: '1:974311107190:android:169b4de8af8319a8dd4d57',
    messagingSenderId: '974311107190',
    projectId: 'gotime-15974',
    storageBucket: 'gotime-15974.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5iDX17kDQHYub4KT5rcswy0kwJNgFx8',
    appId: '1:974311107190:ios:dbbdbaef32db37aadd4d57',
    messagingSenderId: '974311107190',
    projectId: 'gotime-15974',
    storageBucket: 'gotime-15974.firebasestorage.app',
    iosBundleId: 'com.example.gotime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP5iDX17kDQHYub4KT5rcswy0kwJNgFx8',
    appId: '1:974311107190:ios:dbbdbaef32db37aadd4d57',
    messagingSenderId: '974311107190',
    projectId: 'gotime-15974',
    storageBucket: 'gotime-15974.firebasestorage.app',
    iosBundleId: 'com.example.gotime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL6IQNSwRd2EDt77YJBd-T3giehpSJfck',
    appId: '1:974311107190:web:c12ef1dec642b1ebdd4d57',
    messagingSenderId: '974311107190',
    projectId: 'gotime-15974',
    authDomain: 'gotime-15974.firebaseapp.com',
    storageBucket: 'gotime-15974.firebasestorage.app',
  );
}
